[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_mafia = "33FDNiVG3H3qNZYbQJbHVXeJG4n5ZfHL8bXuTieifQ3G"

[programs.localnet]
solana_mafia = "33FDNiVG3H3qNZYbQJbHVXeJG4n5ZfHL8bXuTieifQ3G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-all = "yarn run mocha -t 1000000 tests/"
test-validator = "anchor test"
