"""
Business and BusinessSlot models - mirror on-chain business data.
"""

from datetime import datetime
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .player import Player
from enum import Enum

from sqlalchemy import (
    String, Integer, BigInteger, Boolean, Enum as SQLEnum, 
    ForeignKey, Index, Text
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import BaseModel, TimestampMixin


class BusinessType(Enum):
    """Business types matching on-chain enum."""
    TOBACCO_SHOP = 0       # Lucky Strike Cigars
    FUNERAL_SERVICE = 1    # Eternal Rest Funeral  
    CAR_WORKSHOP = 2       # Midnight Motors Garage
    ITALIAN_RESTAURANT = 3 # Nonna's Secret Kitchen
    GENTLEMEN_CLUB = 4     # Velvet Shadows Club
    CHARITY_FUND = 5       # Angel's Mercy Foundation


class SlotType(Enum):
    """Slot types matching on-chain enum."""
    BASIC = 0
    PREMIUM = 1
    VIP = 2
    LEGENDARY = 3


class Business(BaseModel, TimestampMixin):
    """Business model representing individual business instances."""
    
    __tablename__ = "businesses"
    
    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign keys
    owner_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("users.id", ondelete="CASCADE"),
        comment="Owner's user ID"
    )
    
    player_wallet: Mapped[Optional[str]] = mapped_column(
        String(44),
        ForeignKey("players.wallet", ondelete="CASCADE"),
        comment="Player's wallet address (for Player relationship)"
    )
    
    # Убрано nft_mint поле - NFT больше не используются
    
    # Business properties
    business_type: Mapped[BusinessType] = mapped_column(
        SQLEnum(BusinessType),
        comment="Type of business"
    )
    
    level: Mapped[int] = mapped_column(
        Integer,
        default=0,
        comment="Business upgrade level (0-3, matches contract upgrade_level)"
    )
    
    # Investment tracking
    base_cost: Mapped[int] = mapped_column(
        BigInteger,
        comment="Base cost of business in lamports"
    )
    
    total_invested_amount: Mapped[int] = mapped_column(
        BigInteger,
        comment="Total invested including upgrades in lamports"
    )
    
    upgrade_costs: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="JSON array of upgrade costs"
    )
    
    # Earnings properties
    daily_rate: Mapped[int] = mapped_column(
        Integer,
        comment="Daily rate in basis points (100 = 1%)"
    )
    
    last_claim_time: Mapped[Optional[datetime]] = mapped_column(
        comment="Last earnings claim timestamp"
    )
    
    total_earnings_generated: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        comment="Total earnings generated by this business"
    )
    
    # Status
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        comment="Whether business is active and earning"
    )
    
    # Slot information
    slot_index: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Index of slot this business occupies"
    )
    
    # On-chain tracking
    creation_signature: Mapped[Optional[str]] = mapped_column(
        String(88),
        comment="Transaction signature when business was created"
    )
    
    on_chain_created_at: Mapped[Optional[datetime]] = mapped_column(
        comment="Creation timestamp from blockchain"
    )
    
    last_sync_at: Mapped[Optional[datetime]] = mapped_column(
        comment="Last sync with on-chain data"
    )
    
    # Relationships
    owner_user: Mapped["User"] = relationship(
        "User",
        back_populates="businesses"
    )
    
    player: Mapped[Optional["Player"]] = relationship(
        "Player",
        back_populates="businesses"
    )
    
    # Убрано nft relationship - NFT больше не используются
    
    # Indexes
    __table_args__ = (
        Index("idx_business_owner_active", "owner_id", "is_active"),
        Index("idx_business_player_active", "player_wallet", "is_active"),
        Index("idx_business_type_level", "business_type", "level"),
        Index("idx_business_slot", "owner_id", "slot_index"),
    )
    
    def __repr__(self) -> str:
        return f"<Business(id={self.id}, type={self.business_type.name}, level={self.level})>"
    
    @property
    def name(self) -> str:
        """Get business display name."""
        business_names = {
            BusinessType.TOBACCO_SHOP: "Lucky Strike Cigars",
            BusinessType.FUNERAL_SERVICE: "Eternal Rest Funeral",
            BusinessType.CAR_WORKSHOP: "Midnight Motors Garage", 
            BusinessType.ITALIAN_RESTAURANT: "Nonna's Secret Kitchen",
            BusinessType.GENTLEMEN_CLUB: "Velvet Shadows Club",
            BusinessType.CHARITY_FUND: "Angel's Mercy Foundation"
        }
        return business_names.get(self.business_type, "Unknown Business")
    
    @property
    def daily_earnings_estimate(self) -> int:
        """Calculate estimated daily earnings in lamports."""
        return (self.total_invested_amount * self.daily_rate) // 10000
    
    def calculate_pending_earnings(self, current_time: datetime) -> int:
        """Calculate pending earnings since last claim."""
        if not self.is_active or not self.last_claim_time:
            return 0
        
        time_diff = current_time - self.last_claim_time
        days = time_diff.total_seconds() / 86400  # Convert to days
        
        daily_earnings = self.daily_earnings_estimate
        return int(daily_earnings * days)


class BusinessSlot(BaseModel, TimestampMixin):
    """Business slot model for slot-based system."""
    
    __tablename__ = "business_slots"
    
    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign keys
    owner_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("users.id", ondelete="CASCADE"),
        comment="Owner's user ID"
    )
    
    player_wallet: Mapped[Optional[str]] = mapped_column(
        String(44),
        ForeignKey("players.wallet", ondelete="CASCADE"),
        comment="Player's wallet address (for Player relationship)"
    )
    
    # Slot properties
    slot_index: Mapped[int] = mapped_column(
        Integer,
        comment="Slot index (0-based)"
    )
    
    slot_type: Mapped[SlotType] = mapped_column(
        SQLEnum(SlotType),
        default=SlotType.BASIC,
        comment="Type of slot"
    )
    
    is_unlocked: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        comment="Whether slot is unlocked"
    )
    
    unlock_cost_paid: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        comment="Cost paid to unlock this slot"
    )
    
    # Business in slot
    business_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("businesses.id", ondelete="SET NULL"),
        comment="Business currently in this slot"
    )
    
    # Bonuses
    yield_bonus: Mapped[int] = mapped_column(
        Integer,
        default=0,
        comment="Yield bonus in basis points"
    )
    
    sell_fee_discount: Mapped[int] = mapped_column(
        Integer,
        default=0,
        comment="Sell fee discount percentage"
    )
    
    # Tracking
    unlock_signature: Mapped[Optional[str]] = mapped_column(
        String(88),
        comment="Transaction signature when slot was unlocked"
    )
    
    # Relationships
    owner_user: Mapped["User"] = relationship("User")
    player: Mapped[Optional["Player"]] = relationship(
        "Player",
        foreign_keys=[player_wallet]
    )
    business: Mapped[Optional["Business"]] = relationship("Business")
    
    # Indexes
    __table_args__ = (
        Index("idx_slot_owner_index", "owner_id", "slot_index", unique=True),
        Index("idx_slot_owner_unlocked", "owner_id", "is_unlocked"),
        Index("idx_slot_type", "slot_type"),
    )
    
    def __repr__(self) -> str:
        return f"<BusinessSlot(owner={self.owner_id}, index={self.slot_index}, type={self.slot_type.name})>"
    
    @property
    def is_occupied(self) -> bool:
        """Check if slot has a business."""
        return self.business_id is not None
    
    def get_bonuses(self) -> dict:
        """Get slot bonuses based on type."""
        bonuses = {
            SlotType.BASIC: {"yield": 0, "sell_discount": 0},
            SlotType.PREMIUM: {"yield": 150, "sell_discount": 0},  # +1.5%
            SlotType.VIP: {"yield": 300, "sell_discount": 50},     # +3%, -50% sell fee
            SlotType.LEGENDARY: {"yield": 500, "sell_discount": 100}, # +5%, -100% sell fee
        }
        return bonuses.get(self.slot_type, bonuses[SlotType.BASIC])