"""fix_last_earnings_update_timezone

Revision ID: 28f67a0fde3a
Revises: 9e5d9d7b8d67
Create Date: 2025-08-12 18:46:53.917163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f67a0fde3a'
down_revision: Union[str, None] = '9e5d9d7b8d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'last_earnings_update',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Last earnings update timestamp',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'last_earnings_update',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Last earnings update timestamp',
               existing_nullable=True)
    # ### end Alembic commands ###