"""add_daily_earnings_tracking_tables

Revision ID: 3f7f3e22194e
Revises: 28f67a0fde3a
Create Date: 2025-08-14 23:24:46.586141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7f3e22194e'
down_revision: Union[str, None] = '28f67a0fde3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###