"""Add SOL balance and withdrawal tracking to referral system

Revision ID: 48bbb80a0d28
Revises: e7b57fbf9999
Create Date: 2025-08-12 13:03:24.370325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bbb80a0d28'
down_revision: Union[str, None] = 'e7b57fbf9999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='User identifier (wallet address)'),
    sa.Column('amount_lamports', sa.BigInteger(), nullable=False, comment='Amount withdrawn in lamports'),
    sa.Column('transaction_signature', sa.String(length=88), nullable=True, comment='Solana transaction signature for withdrawal'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, completed, failed'),
    sa.Column('requested_at', sa.DateTime(), nullable=False, comment='When withdrawal was requested'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When withdrawal was processed'),
    sa.Column('processed_by_admin', sa.Boolean(), nullable=False, comment='Whether withdrawal was processed by admin'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if withdrawal failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdrawal_requested', 'referral_withdrawals', ['requested_at'], unique=False)
    op.create_index('idx_withdrawal_signature', 'referral_withdrawals', ['transaction_signature'], unique=False)
    op.create_index('idx_withdrawal_status', 'referral_withdrawals', ['status'], unique=False)
    op.create_index('idx_withdrawal_user', 'referral_withdrawals', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_withdrawals_created_at'), 'referral_withdrawals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_withdrawals_updated_at'), 'referral_withdrawals', ['updated_at'], unique=False)
    op.add_column('referral_stats', sa.Column('sol_balance_lamports', sa.BigInteger(), nullable=False, comment='Internal SOL balance from commissions (in lamports)'))
    op.add_column('referral_stats', sa.Column('total_sol_withdrawn', sa.BigInteger(), nullable=False, comment='Total SOL withdrawn (in lamports)'))
    op.add_column('referral_stats', sa.Column('last_withdrawal_at', sa.DateTime(), nullable=True, comment='Last time SOL was withdrawn'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_stats', 'last_withdrawal_at')
    op.drop_column('referral_stats', 'total_sol_withdrawn')
    op.drop_column('referral_stats', 'sol_balance_lamports')
    op.drop_index(op.f('ix_referral_withdrawals_updated_at'), table_name='referral_withdrawals')
    op.drop_index(op.f('ix_referral_withdrawals_created_at'), table_name='referral_withdrawals')
    op.drop_index('idx_withdrawal_user', table_name='referral_withdrawals')
    op.drop_index('idx_withdrawal_status', table_name='referral_withdrawals')
    op.drop_index('idx_withdrawal_signature', table_name='referral_withdrawals')
    op.drop_index('idx_withdrawal_requested', table_name='referral_withdrawals')
    op.drop_table('referral_withdrawals')
    # ### end Alembic commands ###